<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$plans        = ARM_Username_Generator::get_all_plans();
$saved_map    = get_option( ARM_Username_Generator::OPT_PLAN_PREFIXES, array() );
$last_number  = (int) get_option( ARM_Username_Generator::OPT_LAST_NUMBER, 0 );
$updated      = isset( $_GET['updated'] ) && $_GET['updated'] === '1';
?>
<div class="wrap arm-ugen-wrap">
	<h1><?php esc_html_e( 'Username Generator Settings', 'arm-username-generator' ); ?></h1>

	<?php if ( $updated ) : ?>
		<div class="notice notice-success is-dismissible">
			<p><?php esc_html_e( 'Settings saved successfully.', 'arm-username-generator' ); ?></p>
		</div>
	<?php endif; ?>

	<div class="arm-ugen-intro">
		<p>
			<?php esc_html_e( 'Assign a prefix to each membership plan. When a member registers, a username is automatically generated by combining the prefix with the next number in the global sequence.', 'arm-username-generator' ); ?>
		</p>
		<p>
			<strong><?php esc_html_e( 'Example:', 'arm-username-generator' ); ?></strong>
			<?php esc_html_e( 'Prefix "LM" with counter 1041 → next username is LM1042. Prefix "AM" → AM1043, "FNM" → FNM1044. The number always increments regardless of which plan was used.', 'arm-username-generator' ); ?>
		</p>
	</div>

	<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
		<?php wp_nonce_field( 'arm_ugen_save_settings' ); ?>
		<input type="hidden" name="action" value="arm_ugen_save_settings">

		<!-- ================================================================
		     Counter
		     ============================================================== -->
		<div class="arm-ugen-card">
			<h2><?php esc_html_e( 'Global Sequence Counter', 'arm-username-generator' ); ?></h2>
			<table class="form-table">
				<tr>
					<th scope="row">
						<label for="arm_ugen_last_number">
							<?php esc_html_e( 'Last Allotted Number', 'arm-username-generator' ); ?>
						</label>
					</th>
					<td>
						<input
							type="number"
							id="arm_ugen_last_number"
							name="arm_ugen_last_number"
							value="<?php echo esc_attr( $last_number ); ?>"
							min="0"
							step="1"
							class="small-text"
						>
						<p class="description">
							<?php
							printf(
								/* translators: %d next number */
								esc_html__( 'The last number that was allotted. The next registration will use number %d.', 'arm-username-generator' ),
								$last_number + 1
							);
							?>
						</p>
					</td>
				</tr>
			</table>
		</div>

		<!-- ================================================================
		     Plan → Prefix mapping
		     ============================================================== -->
		<div class="arm-ugen-card">
			<h2><?php esc_html_e( 'Plan Prefix Configuration', 'arm-username-generator' ); ?></h2>

			<?php if ( empty( $plans ) ) : ?>
				<p class="arm-ugen-no-plans">
					<?php esc_html_e( 'No subscription plans found. Please create plans in ARMember first.', 'arm-username-generator' ); ?>
				</p>
			<?php else : ?>
				<p class="description">
					<?php esc_html_e( 'Leave a prefix blank to exclude that plan from auto-username generation.', 'arm-username-generator' ); ?>
				</p>

				<table class="widefat arm-ugen-plan-table">
					<thead>
						<tr>
							<th><?php esc_html_e( 'Plan Name', 'arm-username-generator' ); ?></th>
							<th><?php esc_html_e( 'Prefix', 'arm-username-generator' ); ?></th>
							<th><?php esc_html_e( 'Next Username Preview', 'arm-username-generator' ); ?></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach ( $plans as $plan_id => $plan_name ) :
						$prefix  = isset( $saved_map[ $plan_id ] ) ? $saved_map[ $plan_id ] : '';
						$preview = ( $prefix !== '' ) ? $prefix . ( $last_number + 1 ) : '—';
					?>
						<tr>
							<td>
								<strong><?php echo esc_html( $plan_name ); ?></strong>
								<span class="arm-ugen-plan-id">(ID: <?php echo esc_html( $plan_id ); ?>)</span>
							</td>
							<td>
								<input
									type="text"
									name="arm_ugen_prefixes[<?php echo esc_attr( $plan_id ); ?>]"
									value="<?php echo esc_attr( $prefix ); ?>"
									placeholder="<?php esc_attr_e( 'e.g. LM', 'arm-username-generator' ); ?>"
									maxlength="10"
									class="arm-ugen-prefix-input"
									data-plan-id="<?php echo esc_attr( $plan_id ); ?>"
									data-last-number="<?php echo esc_attr( $last_number ); ?>"
								>
							</td>
							<td class="arm-ugen-preview-cell" id="preview_<?php echo esc_attr( $plan_id ); ?>">
								<code><?php echo esc_html( $preview ); ?></code>
							</td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			<?php endif; ?>
		</div>

		<!-- ================================================================
		     Submit
		     ============================================================== -->
		<?php submit_button( __( 'Save Settings', 'arm-username-generator' ) ); ?>
	</form>
</div>
